[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./adopet-backend"
healthcheckPath = "/api/auth/me"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[[services]]
name = "backend"
